name: Secure CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    security-pipeline:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Build Docker image
              run: docker build -t secure-ci-cd .

            - name: Scan Docker image
              run: ./scan.sh

            - name: Upload Trivy report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: trivy-scan-report
                  path: reports/scan-report.txt
