name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build --no-cache -t secure-ci-cd .

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-ci-cd
          severity: HIGH,CRITICAL
          exit-code: '1'