name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t secure-ci-cd .